spring:
  # Templates reloading during development
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false

  # Static resources reloading during development
  resources:
    static-locations: file:src/main/resources/static/

  datasource:
    platform: h2
    url: jdbc:h2:mem:homenet

  h2:
    console:
      enabled: true
